name: flutter_foundation_website
description: Marketing website for the Flutter Foundation
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  static_shock: any

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
